NON_ENTITY = 'O'
ANY        = 'ANY'
NOTES      = 'notes'
COREF      = 'Coref'
COREF_ATTR = 'Coref_Attr'

SECS      = 'sections'
SENS      = 'sentences'
MENS      = 'mentions'
ENTS      = 'entities'

DOC_ID    = 'document_id'
SEC_ID    = 'section_id'
SEN_ID    = 'sentence_id'
MEN_IDS   = 'mention_ids'
ENT_ID    = 'entity_id'

TXT       = 'text'
SPAN      = 'span'
MEN_TYPE  = 'mention_type'
ENT_TYPE  = 'entity_type'

MEM_MEN_IDS   = 'member_mention_ids'
ENT_TYPE_MRG  = 'entity_type_merged'
DIR_MEN_PAIRS = 'directed_mention_pairs'
HAS_NAME      = 'has_name'
HAS_REF       = 'has_ref'
REF_URL       = 'ref_url'
REF_URLS      = 'ref_urls'
REF_TYPE      = 'ref_type'
NIL           = 'NIL'
